name: CI (Pull Request)

on:
  pull_request:
    branches: ["**"]

jobs:
  precommit:
    uses: ./.github/workflows/precommit.yml

  expanded:
    name: Expanded checks (stub)
    needs: precommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Black (check only)
        run: |
          uvx black --check .

      - name: Ruff (lint only)
        run: |
          uvx ruff check .

      - name: Placeholder for unit tests and integration matrix
        run: echo "TODO: add pytest, packaging checks, AT-SPI integration matrix (Linux)."

